
global_costmap:
  plugins:
    - {name: static_layer,       type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer,       type: "costmap_2d::ObstacleLayer"}


  publish_frequency: 1.0
  footprint: [[-0.6, -0.6], [-0.6, 0.6], [0.6, 0.6], [0.6, -0.6]]
  global_frame: map
  robot_base_frame: base_link


  transform_tolerance: 0.2
  map_type: costmap

  obstacle_layer:
    enabled: true
    obstacle_range: 3.0
    raytrace_range: 4.0
    inflation_radius: 0.2
    track_unknown_space: true
    combination_method: 1

    observation_sources: laser_scan_sensor
    laser_scan_sensor: {data_type: LaserScan, topic: scan_multi, marking: true, clearing: true}




  inflation_layer:
    enabled:              true
    cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

  static_layer:
    enabled:              true
    map_topic:            "/map"



local_costmap:
  plugins:
#    - {name: static_layer,       type: "costmap_2d::StaticLayer"}
    - {name: inflation_layer,       type: "costmap_2d::InflationLayer"}
    - {name: obstacle_layer,       type: "costmap_2d::ObstacleLayer"}
    - {name: tall_obstacle_layer,    type: "costmap_2d::ObstacleLayer"}
  publish_frequency: 10.0
  footprint: [[-0.6, -0.6], [-0.6, 0.6], [0.6, 0.6], [0.6, -0.6]]

  transform_tolerance: 0.2
  map_type: costmap
  rolling_window: true




  obstacle_layer:
    enabled: true
    obstacle_range: 3.0
    raytrace_range: 4.0
    inflation_radius: 0.2
    track_unknown_space: true
    combination_method: 1

    observation_sources: laser_scan_sensor_left laser_scan_sensor_right
    laser_scan_sensor_left: {data_type: LaserScan, topic: monokl_l/scan, marking: true, clearing: true}
    laser_scan_sensor_right: {data_type: LaserScan, topic: monokl_r/scan, marking: true, clearing: true}




  tall_obstacle_layer:

    map_topic: tall_map
    enabled: true
    obstacle_range: 3.0
    raytrace_range: 4.0
    inflation_radius: 0.7
    track_unknown_space: false
    combination_method: 1

    observation_sources: point_cld
    point_cld: {data_type: PointCloud2, topic: head_kinect/depth/points, min_obstacle_height: 0.5, marking: true, clearing: true}


  inflation_layer:
    enabled:              true
    cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.

#    observation_sources: laser_scan_sensor
#    laser_scan_sensor: {data_type: LaserScan, topic: monokl_l/scan, marking: true, clearing: true}

#  static_layer:
#    enabled:              true
#    cost_scaling_factor:  10.0  # exponential rate at which the obstacle cost drops off (default: 10)
#    inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.
#    map_topic:            "/map"